---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r}
## load Required Libraries 
library(plyr)
library(ggplot2)
library(timeDate)
## Download, unzip and cleanup
zip <- 'activity.zip'
url = 'https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip'
download.file(url, zip, method='curl')
unzip(zip)
file.remove(zip)
rm(list=ls())
## Read in the data and summarise by day
activity <- read.csv("activity.csv")
#activity[is.na(activity)] <- 0
```

## What is mean total number of steps taken per day?

```{r}
daily_activity <- ddply(activity, "date", summarize, daily.steps = sum(steps))
qplot(daily.steps, data=daily_activity, geom="histogram", binwidth=1000)
mean(daily_activity$daily.steps, na.rm=TRUE)
median(daily_activity$daily.steps, na.rm=TRUE)
```

## What is the average daily activity pattern?

```{r}
average.day <- ddply(activity, "interval", summarize, steps = mean(steps, na.rm=TRUE))
ggplot(average.day, aes(interval,steps)) + geom_line() + xlab("Interval") +ylab("Average Steps")
```

## Imputing missing values

```{r}
sum(is.na(activity$steps))
impute.mean <- function(x) replace(x, is.na(x), mean(x, na.rm = TRUE))
activity2 <- ddply(activity, "interval", transform, steps = impute.mean(steps))
daily_activity2 <- ddply(activity2, "date", summarize, daily.steps = sum(steps))
qplot(daily.steps, data=daily_activity2, geom="histogram", binwidth=1000)
mean(daily_activity2$daily.steps, na.rm=TRUE)
median(daily_activity2$daily.steps, na.rm=TRUE)
```

## Are there differences in activity patterns between weekdays and weekends?

```{r}
activity2$weekday <- factor(isWeekday(activity2$date,wday=1:5),
                            labels=c('Weekend', 'Weekday'))
average.weekday <- ddply(activity2, c("interval","weekday"), summarize, steps = mean(steps))
ggplot(average.weekday, aes(interval,steps)) + geom_line(color="blue") + xlab("Interval") +ylab("Average Steps") + facet_wrap(~weekday, nrow=2)
```